
/****** Object:  Table [dbo].[xref_LoyaltyCode_paths]    Script Date: 4/1/2021 11:13:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [DBO].[XREF_LOYALTYCODE_PATHS](
	[FEATURE_NAME] [VARCHAR](50) NULL,
	[CODE_TYPE] [VARCHAR](50) NULL,
	[ACT_PATH] [VARCHAR](500) NULL,
	[SITE_SPECIFIC_CODE] [VARCHAR](10) NULL,
	[COMMENT] [VARCHAR](250) NULL,
) ON [PRIMARY]

GO

CREATE CLUSTERED INDEX [NDX_PATH] ON [DBO].[XREF_LOYALTYCODE_PATHS]
(
	[ACT_PATH] ASC,
	[FEATURE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

SET ANSI_PADDING OFF
GO


